### ISSUE TITLE
[migration] Do not see history for previous repos

### ISSUE THREAD

**Issue by seelder** [SoftwareEngineeringToolDemos/ICSE-2013-VISSUELIZER#5]
This does not contain the full history of the project.

**Comment by gsrajadh** [comment]
Hi, You can see the author's commits if you go to the history of the Repo. Here is a screenshot of the history:
<img width="1280" alt="screen shot 2015-10-22 at 11 26 56 pm" src="https://cloud.githubusercontent.com/assets/11032855/10683852/7cf38f40-7914-11e5-9fe9-b9d2db17ceef.png">

**Comment by seelder** [comment]
OK. I wanted to make sure we got this one copied over since it was the reason for the second repo.
